//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maaif.WebReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://finaclews.org", ConfigurationName="WebReference.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name BILLER_ID from namespace http://finaclews.org is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://finaclews.org/UbaVasPayment", ReplyAction="*")]
        Maaif.WebReference.UbaVasPaymentResponse UbaVasPayment(Maaif.WebReference.UbaVasPaymentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://finaclews.org/UbaVasPayment", ReplyAction="*")]
        System.Threading.Tasks.Task<Maaif.WebReference.UbaVasPaymentResponse> UbaVasPaymentAsync(Maaif.WebReference.UbaVasPaymentRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://finaclews.org is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://finaclews.org/GetBalance", ReplyAction="*")]
        Maaif.WebReference.GetBalanceResponse GetBalance(Maaif.WebReference.GetBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://finaclews.org/GetBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<Maaif.WebReference.GetBalanceResponse> GetBalanceAsync(Maaif.WebReference.GetBalanceRequest request);
        
        // CODEGEN: Generating message contract since element name bank_id from namespace http://finaclews.org is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://finaclews.org/AccountOpening", ReplyAction="*")]
        Maaif.WebReference.AccountOpeningResponse AccountOpening(Maaif.WebReference.AccountOpeningRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://finaclews.org/AccountOpening", ReplyAction="*")]
        System.Threading.Tasks.Task<Maaif.WebReference.AccountOpeningResponse> AccountOpeningAsync(Maaif.WebReference.AccountOpeningRequest request);
        
        // CODEGEN: Generating message contract since element name UnbsGetProductsResult from namespace http://finaclews.org is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://finaclews.org/UnbsGetProducts", ReplyAction="*")]
        Maaif.WebReference.UnbsGetProductsResponse UnbsGetProducts(Maaif.WebReference.UnbsGetProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://finaclews.org/UnbsGetProducts", ReplyAction="*")]
        System.Threading.Tasks.Task<Maaif.WebReference.UnbsGetProductsResponse> UnbsGetProductsAsync(Maaif.WebReference.UnbsGetProductsRequest request);
        
        // CODEGEN: Generating message contract since element name tag from namespace http://finaclews.org is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://finaclews.org/UnbsGetProductPerTag", ReplyAction="*")]
        Maaif.WebReference.UnbsGetProductPerTagResponse UnbsGetProductPerTag(Maaif.WebReference.UnbsGetProductPerTagRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://finaclews.org/UnbsGetProductPerTag", ReplyAction="*")]
        System.Threading.Tasks.Task<Maaif.WebReference.UnbsGetProductPerTagResponse> UnbsGetProductPerTagAsync(Maaif.WebReference.UnbsGetProductPerTagRequest request);
        
        // CODEGEN: Generating message contract since element name nationalId from namespace http://finaclews.org is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://finaclews.org/NiraIntegrationGetPerson", ReplyAction="*")]
        Maaif.WebReference.NiraIntegrationGetPersonResponse NiraIntegrationGetPerson(Maaif.WebReference.NiraIntegrationGetPersonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://finaclews.org/NiraIntegrationGetPerson", ReplyAction="*")]
        System.Threading.Tasks.Task<Maaif.WebReference.NiraIntegrationGetPersonResponse> NiraIntegrationGetPersonAsync(Maaif.WebReference.NiraIntegrationGetPersonRequest request);
        
        // CODEGEN: Generating message contract since element name NewPassword from namespace http://finaclews.org is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://finaclews.org/NiraIntegrationChangePassword", ReplyAction="*")]
        Maaif.WebReference.NiraIntegrationChangePasswordResponse NiraIntegrationChangePassword(Maaif.WebReference.NiraIntegrationChangePasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://finaclews.org/NiraIntegrationChangePassword", ReplyAction="*")]
        System.Threading.Tasks.Task<Maaif.WebReference.NiraIntegrationChangePasswordResponse> NiraIntegrationChangePasswordAsync(Maaif.WebReference.NiraIntegrationChangePasswordRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UbaVasPaymentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UbaVasPayment", Namespace="http://finaclews.org", Order=0)]
        public Maaif.WebReference.UbaVasPaymentRequestBody Body;
        
        public UbaVasPaymentRequest() {
        }
        
        public UbaVasPaymentRequest(Maaif.WebReference.UbaVasPaymentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://finaclews.org")]
    public partial class UbaVasPaymentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BILLER_ID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string AMOUNT;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ACCOUNT_NO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string COUNTRY_CODE;
        
        public UbaVasPaymentRequestBody() {
        }
        
        public UbaVasPaymentRequestBody(string BILLER_ID, string AMOUNT, string ACCOUNT_NO, string COUNTRY_CODE) {
            this.BILLER_ID = BILLER_ID;
            this.AMOUNT = AMOUNT;
            this.ACCOUNT_NO = ACCOUNT_NO;
            this.COUNTRY_CODE = COUNTRY_CODE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UbaVasPaymentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UbaVasPaymentResponse", Namespace="http://finaclews.org", Order=0)]
        public Maaif.WebReference.UbaVasPaymentResponseBody Body;
        
        public UbaVasPaymentResponse() {
        }
        
        public UbaVasPaymentResponse(Maaif.WebReference.UbaVasPaymentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://finaclews.org")]
    public partial class UbaVasPaymentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UbaVasPaymentResult;
        
        public UbaVasPaymentResponseBody() {
        }
        
        public UbaVasPaymentResponseBody(string UbaVasPaymentResult) {
            this.UbaVasPaymentResult = UbaVasPaymentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBalance", Namespace="http://finaclews.org", Order=0)]
        public Maaif.WebReference.GetBalanceRequestBody Body;
        
        public GetBalanceRequest() {
        }
        
        public GetBalanceRequest(Maaif.WebReference.GetBalanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://finaclews.org")]
    public partial class GetBalanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PROCESSING_CODE;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DR_ACCT_NUM;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string TRAN_CRNCY_CODE;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string COUNTRY_CODE;
        
        public GetBalanceRequestBody() {
        }
        
        public GetBalanceRequestBody(string username, string password, string PROCESSING_CODE, string DR_ACCT_NUM, string TRAN_CRNCY_CODE, string COUNTRY_CODE) {
            this.username = username;
            this.password = password;
            this.PROCESSING_CODE = PROCESSING_CODE;
            this.DR_ACCT_NUM = DR_ACCT_NUM;
            this.TRAN_CRNCY_CODE = TRAN_CRNCY_CODE;
            this.COUNTRY_CODE = COUNTRY_CODE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBalanceResponse", Namespace="http://finaclews.org", Order=0)]
        public Maaif.WebReference.GetBalanceResponseBody Body;
        
        public GetBalanceResponse() {
        }
        
        public GetBalanceResponse(Maaif.WebReference.GetBalanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://finaclews.org")]
    public partial class GetBalanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetBalanceResult;
        
        public GetBalanceResponseBody() {
        }
        
        public GetBalanceResponseBody(string GetBalanceResult) {
            this.GetBalanceResult = GetBalanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AccountOpeningRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AccountOpening", Namespace="http://finaclews.org", Order=0)]
        public Maaif.WebReference.AccountOpeningRequestBody Body;
        
        public AccountOpeningRequest() {
        }
        
        public AccountOpeningRequest(Maaif.WebReference.AccountOpeningRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://finaclews.org")]
    public partial class AccountOpeningRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string bank_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string source_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string last_name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string first_name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string middle_name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string cust_addr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string gender;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string cust_title_code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string cust_cntry_code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string cust_phone_num;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string email_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string dob;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string ac_manager_code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string sol_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string schm_code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string gl_sub_head_code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string crncy_code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string marital_status;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string passport_num;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string requestid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string acct_type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string freetext;
        
        public AccountOpeningRequestBody() {
        }
        
        public AccountOpeningRequestBody(
                    string bank_id, 
                    string source_id, 
                    string last_name, 
                    string first_name, 
                    string middle_name, 
                    string cust_addr, 
                    string gender, 
                    string cust_title_code, 
                    string cust_cntry_code, 
                    string cust_phone_num, 
                    string email_id, 
                    string dob, 
                    string ac_manager_code, 
                    string sol_id, 
                    string schm_code, 
                    string gl_sub_head_code, 
                    string crncy_code, 
                    string marital_status, 
                    string passport_num, 
                    string requestid, 
                    string acct_type, 
                    string freetext) {
            this.bank_id = bank_id;
            this.source_id = source_id;
            this.last_name = last_name;
            this.first_name = first_name;
            this.middle_name = middle_name;
            this.cust_addr = cust_addr;
            this.gender = gender;
            this.cust_title_code = cust_title_code;
            this.cust_cntry_code = cust_cntry_code;
            this.cust_phone_num = cust_phone_num;
            this.email_id = email_id;
            this.dob = dob;
            this.ac_manager_code = ac_manager_code;
            this.sol_id = sol_id;
            this.schm_code = schm_code;
            this.gl_sub_head_code = gl_sub_head_code;
            this.crncy_code = crncy_code;
            this.marital_status = marital_status;
            this.passport_num = passport_num;
            this.requestid = requestid;
            this.acct_type = acct_type;
            this.freetext = freetext;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AccountOpeningResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AccountOpeningResponse", Namespace="http://finaclews.org", Order=0)]
        public Maaif.WebReference.AccountOpeningResponseBody Body;
        
        public AccountOpeningResponse() {
        }
        
        public AccountOpeningResponse(Maaif.WebReference.AccountOpeningResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://finaclews.org")]
    public partial class AccountOpeningResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AccountOpeningResult;
        
        public AccountOpeningResponseBody() {
        }
        
        public AccountOpeningResponseBody(string AccountOpeningResult) {
            this.AccountOpeningResult = AccountOpeningResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UnbsGetProductsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UnbsGetProducts", Namespace="http://finaclews.org", Order=0)]
        public Maaif.WebReference.UnbsGetProductsRequestBody Body;
        
        public UnbsGetProductsRequest() {
        }
        
        public UnbsGetProductsRequest(Maaif.WebReference.UnbsGetProductsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UnbsGetProductsRequestBody {
        
        public UnbsGetProductsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UnbsGetProductsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UnbsGetProductsResponse", Namespace="http://finaclews.org", Order=0)]
        public Maaif.WebReference.UnbsGetProductsResponseBody Body;
        
        public UnbsGetProductsResponse() {
        }
        
        public UnbsGetProductsResponse(Maaif.WebReference.UnbsGetProductsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://finaclews.org")]
    public partial class UnbsGetProductsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UnbsGetProductsResult;
        
        public UnbsGetProductsResponseBody() {
        }
        
        public UnbsGetProductsResponseBody(string UnbsGetProductsResult) {
            this.UnbsGetProductsResult = UnbsGetProductsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UnbsGetProductPerTagRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UnbsGetProductPerTag", Namespace="http://finaclews.org", Order=0)]
        public Maaif.WebReference.UnbsGetProductPerTagRequestBody Body;
        
        public UnbsGetProductPerTagRequest() {
        }
        
        public UnbsGetProductPerTagRequest(Maaif.WebReference.UnbsGetProductPerTagRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://finaclews.org")]
    public partial class UnbsGetProductPerTagRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tag;
        
        public UnbsGetProductPerTagRequestBody() {
        }
        
        public UnbsGetProductPerTagRequestBody(string tag) {
            this.tag = tag;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UnbsGetProductPerTagResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UnbsGetProductPerTagResponse", Namespace="http://finaclews.org", Order=0)]
        public Maaif.WebReference.UnbsGetProductPerTagResponseBody Body;
        
        public UnbsGetProductPerTagResponse() {
        }
        
        public UnbsGetProductPerTagResponse(Maaif.WebReference.UnbsGetProductPerTagResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://finaclews.org")]
    public partial class UnbsGetProductPerTagResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UnbsGetProductPerTagResult;
        
        public UnbsGetProductPerTagResponseBody() {
        }
        
        public UnbsGetProductPerTagResponseBody(string UnbsGetProductPerTagResult) {
            this.UnbsGetProductPerTagResult = UnbsGetProductPerTagResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NiraIntegrationGetPersonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NiraIntegrationGetPerson", Namespace="http://finaclews.org", Order=0)]
        public Maaif.WebReference.NiraIntegrationGetPersonRequestBody Body;
        
        public NiraIntegrationGetPersonRequest() {
        }
        
        public NiraIntegrationGetPersonRequest(Maaif.WebReference.NiraIntegrationGetPersonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://finaclews.org")]
    public partial class NiraIntegrationGetPersonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nationalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DocumentID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string givenNames;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string otherNames;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime dateOfBirth;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string surName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string password;
        
        public NiraIntegrationGetPersonRequestBody() {
        }
        
        public NiraIntegrationGetPersonRequestBody(string nationalId, string DocumentID, string givenNames, string otherNames, System.DateTime dateOfBirth, string surName, string username, string password) {
            this.nationalId = nationalId;
            this.DocumentID = DocumentID;
            this.givenNames = givenNames;
            this.otherNames = otherNames;
            this.dateOfBirth = dateOfBirth;
            this.surName = surName;
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NiraIntegrationGetPersonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NiraIntegrationGetPersonResponse", Namespace="http://finaclews.org", Order=0)]
        public Maaif.WebReference.NiraIntegrationGetPersonResponseBody Body;
        
        public NiraIntegrationGetPersonResponse() {
        }
        
        public NiraIntegrationGetPersonResponse(Maaif.WebReference.NiraIntegrationGetPersonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://finaclews.org")]
    public partial class NiraIntegrationGetPersonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NiraIntegrationGetPersonResult;
        
        public NiraIntegrationGetPersonResponseBody() {
        }
        
        public NiraIntegrationGetPersonResponseBody(string NiraIntegrationGetPersonResult) {
            this.NiraIntegrationGetPersonResult = NiraIntegrationGetPersonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NiraIntegrationChangePasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NiraIntegrationChangePassword", Namespace="http://finaclews.org", Order=0)]
        public Maaif.WebReference.NiraIntegrationChangePasswordRequestBody Body;
        
        public NiraIntegrationChangePasswordRequest() {
        }
        
        public NiraIntegrationChangePasswordRequest(Maaif.WebReference.NiraIntegrationChangePasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://finaclews.org")]
    public partial class NiraIntegrationChangePasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NewPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        public NiraIntegrationChangePasswordRequestBody() {
        }
        
        public NiraIntegrationChangePasswordRequestBody(string NewPassword, string username, string password) {
            this.NewPassword = NewPassword;
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NiraIntegrationChangePasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NiraIntegrationChangePasswordResponse", Namespace="http://finaclews.org", Order=0)]
        public Maaif.WebReference.NiraIntegrationChangePasswordResponseBody Body;
        
        public NiraIntegrationChangePasswordResponse() {
        }
        
        public NiraIntegrationChangePasswordResponse(Maaif.WebReference.NiraIntegrationChangePasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://finaclews.org")]
    public partial class NiraIntegrationChangePasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NiraIntegrationChangePasswordResult;
        
        public NiraIntegrationChangePasswordResponseBody() {
        }
        
        public NiraIntegrationChangePasswordResponseBody(string NiraIntegrationChangePasswordResult) {
            this.NiraIntegrationChangePasswordResult = NiraIntegrationChangePasswordResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : Maaif.WebReference.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<Maaif.WebReference.WebServiceSoap>, Maaif.WebReference.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Maaif.WebReference.UbaVasPaymentResponse Maaif.WebReference.WebServiceSoap.UbaVasPayment(Maaif.WebReference.UbaVasPaymentRequest request) {
            return base.Channel.UbaVasPayment(request);
        }
        
        public string UbaVasPayment(string BILLER_ID, string AMOUNT, string ACCOUNT_NO, string COUNTRY_CODE) {
            Maaif.WebReference.UbaVasPaymentRequest inValue = new Maaif.WebReference.UbaVasPaymentRequest();
            inValue.Body = new Maaif.WebReference.UbaVasPaymentRequestBody();
            inValue.Body.BILLER_ID = BILLER_ID;
            inValue.Body.AMOUNT = AMOUNT;
            inValue.Body.ACCOUNT_NO = ACCOUNT_NO;
            inValue.Body.COUNTRY_CODE = COUNTRY_CODE;
            Maaif.WebReference.UbaVasPaymentResponse retVal = ((Maaif.WebReference.WebServiceSoap)(this)).UbaVasPayment(inValue);
            return retVal.Body.UbaVasPaymentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Maaif.WebReference.UbaVasPaymentResponse> Maaif.WebReference.WebServiceSoap.UbaVasPaymentAsync(Maaif.WebReference.UbaVasPaymentRequest request) {
            return base.Channel.UbaVasPaymentAsync(request);
        }
        
        public System.Threading.Tasks.Task<Maaif.WebReference.UbaVasPaymentResponse> UbaVasPaymentAsync(string BILLER_ID, string AMOUNT, string ACCOUNT_NO, string COUNTRY_CODE) {
            Maaif.WebReference.UbaVasPaymentRequest inValue = new Maaif.WebReference.UbaVasPaymentRequest();
            inValue.Body = new Maaif.WebReference.UbaVasPaymentRequestBody();
            inValue.Body.BILLER_ID = BILLER_ID;
            inValue.Body.AMOUNT = AMOUNT;
            inValue.Body.ACCOUNT_NO = ACCOUNT_NO;
            inValue.Body.COUNTRY_CODE = COUNTRY_CODE;
            return ((Maaif.WebReference.WebServiceSoap)(this)).UbaVasPaymentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Maaif.WebReference.GetBalanceResponse Maaif.WebReference.WebServiceSoap.GetBalance(Maaif.WebReference.GetBalanceRequest request) {
            return base.Channel.GetBalance(request);
        }
        
        public string GetBalance(string username, string password, string PROCESSING_CODE, string DR_ACCT_NUM, string TRAN_CRNCY_CODE, string COUNTRY_CODE) {
            Maaif.WebReference.GetBalanceRequest inValue = new Maaif.WebReference.GetBalanceRequest();
            inValue.Body = new Maaif.WebReference.GetBalanceRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.PROCESSING_CODE = PROCESSING_CODE;
            inValue.Body.DR_ACCT_NUM = DR_ACCT_NUM;
            inValue.Body.TRAN_CRNCY_CODE = TRAN_CRNCY_CODE;
            inValue.Body.COUNTRY_CODE = COUNTRY_CODE;
            Maaif.WebReference.GetBalanceResponse retVal = ((Maaif.WebReference.WebServiceSoap)(this)).GetBalance(inValue);
            return retVal.Body.GetBalanceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Maaif.WebReference.GetBalanceResponse> Maaif.WebReference.WebServiceSoap.GetBalanceAsync(Maaif.WebReference.GetBalanceRequest request) {
            return base.Channel.GetBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<Maaif.WebReference.GetBalanceResponse> GetBalanceAsync(string username, string password, string PROCESSING_CODE, string DR_ACCT_NUM, string TRAN_CRNCY_CODE, string COUNTRY_CODE) {
            Maaif.WebReference.GetBalanceRequest inValue = new Maaif.WebReference.GetBalanceRequest();
            inValue.Body = new Maaif.WebReference.GetBalanceRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.PROCESSING_CODE = PROCESSING_CODE;
            inValue.Body.DR_ACCT_NUM = DR_ACCT_NUM;
            inValue.Body.TRAN_CRNCY_CODE = TRAN_CRNCY_CODE;
            inValue.Body.COUNTRY_CODE = COUNTRY_CODE;
            return ((Maaif.WebReference.WebServiceSoap)(this)).GetBalanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Maaif.WebReference.AccountOpeningResponse Maaif.WebReference.WebServiceSoap.AccountOpening(Maaif.WebReference.AccountOpeningRequest request) {
            return base.Channel.AccountOpening(request);
        }
        
        public string AccountOpening(
                    string bank_id, 
                    string source_id, 
                    string last_name, 
                    string first_name, 
                    string middle_name, 
                    string cust_addr, 
                    string gender, 
                    string cust_title_code, 
                    string cust_cntry_code, 
                    string cust_phone_num, 
                    string email_id, 
                    string dob, 
                    string ac_manager_code, 
                    string sol_id, 
                    string schm_code, 
                    string gl_sub_head_code, 
                    string crncy_code, 
                    string marital_status, 
                    string passport_num, 
                    string requestid, 
                    string acct_type, 
                    string freetext) {
            Maaif.WebReference.AccountOpeningRequest inValue = new Maaif.WebReference.AccountOpeningRequest();
            inValue.Body = new Maaif.WebReference.AccountOpeningRequestBody();
            inValue.Body.bank_id = bank_id;
            inValue.Body.source_id = source_id;
            inValue.Body.last_name = last_name;
            inValue.Body.first_name = first_name;
            inValue.Body.middle_name = middle_name;
            inValue.Body.cust_addr = cust_addr;
            inValue.Body.gender = gender;
            inValue.Body.cust_title_code = cust_title_code;
            inValue.Body.cust_cntry_code = cust_cntry_code;
            inValue.Body.cust_phone_num = cust_phone_num;
            inValue.Body.email_id = email_id;
            inValue.Body.dob = dob;
            inValue.Body.ac_manager_code = ac_manager_code;
            inValue.Body.sol_id = sol_id;
            inValue.Body.schm_code = schm_code;
            inValue.Body.gl_sub_head_code = gl_sub_head_code;
            inValue.Body.crncy_code = crncy_code;
            inValue.Body.marital_status = marital_status;
            inValue.Body.passport_num = passport_num;
            inValue.Body.requestid = requestid;
            inValue.Body.acct_type = acct_type;
            inValue.Body.freetext = freetext;
            Maaif.WebReference.AccountOpeningResponse retVal = ((Maaif.WebReference.WebServiceSoap)(this)).AccountOpening(inValue);
            return retVal.Body.AccountOpeningResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Maaif.WebReference.AccountOpeningResponse> Maaif.WebReference.WebServiceSoap.AccountOpeningAsync(Maaif.WebReference.AccountOpeningRequest request) {
            return base.Channel.AccountOpeningAsync(request);
        }
        
        public System.Threading.Tasks.Task<Maaif.WebReference.AccountOpeningResponse> AccountOpeningAsync(
                    string bank_id, 
                    string source_id, 
                    string last_name, 
                    string first_name, 
                    string middle_name, 
                    string cust_addr, 
                    string gender, 
                    string cust_title_code, 
                    string cust_cntry_code, 
                    string cust_phone_num, 
                    string email_id, 
                    string dob, 
                    string ac_manager_code, 
                    string sol_id, 
                    string schm_code, 
                    string gl_sub_head_code, 
                    string crncy_code, 
                    string marital_status, 
                    string passport_num, 
                    string requestid, 
                    string acct_type, 
                    string freetext) {
            Maaif.WebReference.AccountOpeningRequest inValue = new Maaif.WebReference.AccountOpeningRequest();
            inValue.Body = new Maaif.WebReference.AccountOpeningRequestBody();
            inValue.Body.bank_id = bank_id;
            inValue.Body.source_id = source_id;
            inValue.Body.last_name = last_name;
            inValue.Body.first_name = first_name;
            inValue.Body.middle_name = middle_name;
            inValue.Body.cust_addr = cust_addr;
            inValue.Body.gender = gender;
            inValue.Body.cust_title_code = cust_title_code;
            inValue.Body.cust_cntry_code = cust_cntry_code;
            inValue.Body.cust_phone_num = cust_phone_num;
            inValue.Body.email_id = email_id;
            inValue.Body.dob = dob;
            inValue.Body.ac_manager_code = ac_manager_code;
            inValue.Body.sol_id = sol_id;
            inValue.Body.schm_code = schm_code;
            inValue.Body.gl_sub_head_code = gl_sub_head_code;
            inValue.Body.crncy_code = crncy_code;
            inValue.Body.marital_status = marital_status;
            inValue.Body.passport_num = passport_num;
            inValue.Body.requestid = requestid;
            inValue.Body.acct_type = acct_type;
            inValue.Body.freetext = freetext;
            return ((Maaif.WebReference.WebServiceSoap)(this)).AccountOpeningAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Maaif.WebReference.UnbsGetProductsResponse Maaif.WebReference.WebServiceSoap.UnbsGetProducts(Maaif.WebReference.UnbsGetProductsRequest request) {
            return base.Channel.UnbsGetProducts(request);
        }
        
        public string UnbsGetProducts() {
            Maaif.WebReference.UnbsGetProductsRequest inValue = new Maaif.WebReference.UnbsGetProductsRequest();
            inValue.Body = new Maaif.WebReference.UnbsGetProductsRequestBody();
            Maaif.WebReference.UnbsGetProductsResponse retVal = ((Maaif.WebReference.WebServiceSoap)(this)).UnbsGetProducts(inValue);
            return retVal.Body.UnbsGetProductsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Maaif.WebReference.UnbsGetProductsResponse> Maaif.WebReference.WebServiceSoap.UnbsGetProductsAsync(Maaif.WebReference.UnbsGetProductsRequest request) {
            return base.Channel.UnbsGetProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Maaif.WebReference.UnbsGetProductsResponse> UnbsGetProductsAsync() {
            Maaif.WebReference.UnbsGetProductsRequest inValue = new Maaif.WebReference.UnbsGetProductsRequest();
            inValue.Body = new Maaif.WebReference.UnbsGetProductsRequestBody();
            return ((Maaif.WebReference.WebServiceSoap)(this)).UnbsGetProductsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Maaif.WebReference.UnbsGetProductPerTagResponse Maaif.WebReference.WebServiceSoap.UnbsGetProductPerTag(Maaif.WebReference.UnbsGetProductPerTagRequest request) {
            return base.Channel.UnbsGetProductPerTag(request);
        }
        
        public string UnbsGetProductPerTag(string tag) {
            Maaif.WebReference.UnbsGetProductPerTagRequest inValue = new Maaif.WebReference.UnbsGetProductPerTagRequest();
            inValue.Body = new Maaif.WebReference.UnbsGetProductPerTagRequestBody();
            inValue.Body.tag = tag;
            Maaif.WebReference.UnbsGetProductPerTagResponse retVal = ((Maaif.WebReference.WebServiceSoap)(this)).UnbsGetProductPerTag(inValue);
            return retVal.Body.UnbsGetProductPerTagResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Maaif.WebReference.UnbsGetProductPerTagResponse> Maaif.WebReference.WebServiceSoap.UnbsGetProductPerTagAsync(Maaif.WebReference.UnbsGetProductPerTagRequest request) {
            return base.Channel.UnbsGetProductPerTagAsync(request);
        }
        
        public System.Threading.Tasks.Task<Maaif.WebReference.UnbsGetProductPerTagResponse> UnbsGetProductPerTagAsync(string tag) {
            Maaif.WebReference.UnbsGetProductPerTagRequest inValue = new Maaif.WebReference.UnbsGetProductPerTagRequest();
            inValue.Body = new Maaif.WebReference.UnbsGetProductPerTagRequestBody();
            inValue.Body.tag = tag;
            return ((Maaif.WebReference.WebServiceSoap)(this)).UnbsGetProductPerTagAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Maaif.WebReference.NiraIntegrationGetPersonResponse Maaif.WebReference.WebServiceSoap.NiraIntegrationGetPerson(Maaif.WebReference.NiraIntegrationGetPersonRequest request) {
            return base.Channel.NiraIntegrationGetPerson(request);
        }
        
        public string NiraIntegrationGetPerson(string nationalId, string DocumentID, string givenNames, string otherNames, System.DateTime dateOfBirth, string surName, string username, string password) {
            Maaif.WebReference.NiraIntegrationGetPersonRequest inValue = new Maaif.WebReference.NiraIntegrationGetPersonRequest();
            inValue.Body = new Maaif.WebReference.NiraIntegrationGetPersonRequestBody();
            inValue.Body.nationalId = nationalId;
            inValue.Body.DocumentID = DocumentID;
            inValue.Body.givenNames = givenNames;
            inValue.Body.otherNames = otherNames;
            inValue.Body.dateOfBirth = dateOfBirth;
            inValue.Body.surName = surName;
            inValue.Body.username = username;
            inValue.Body.password = password;
            Maaif.WebReference.NiraIntegrationGetPersonResponse retVal = ((Maaif.WebReference.WebServiceSoap)(this)).NiraIntegrationGetPerson(inValue);
            return retVal.Body.NiraIntegrationGetPersonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Maaif.WebReference.NiraIntegrationGetPersonResponse> Maaif.WebReference.WebServiceSoap.NiraIntegrationGetPersonAsync(Maaif.WebReference.NiraIntegrationGetPersonRequest request) {
            return base.Channel.NiraIntegrationGetPersonAsync(request);
        }
        
        public System.Threading.Tasks.Task<Maaif.WebReference.NiraIntegrationGetPersonResponse> NiraIntegrationGetPersonAsync(string nationalId, string DocumentID, string givenNames, string otherNames, System.DateTime dateOfBirth, string surName, string username, string password) {
            Maaif.WebReference.NiraIntegrationGetPersonRequest inValue = new Maaif.WebReference.NiraIntegrationGetPersonRequest();
            inValue.Body = new Maaif.WebReference.NiraIntegrationGetPersonRequestBody();
            inValue.Body.nationalId = nationalId;
            inValue.Body.DocumentID = DocumentID;
            inValue.Body.givenNames = givenNames;
            inValue.Body.otherNames = otherNames;
            inValue.Body.dateOfBirth = dateOfBirth;
            inValue.Body.surName = surName;
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((Maaif.WebReference.WebServiceSoap)(this)).NiraIntegrationGetPersonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Maaif.WebReference.NiraIntegrationChangePasswordResponse Maaif.WebReference.WebServiceSoap.NiraIntegrationChangePassword(Maaif.WebReference.NiraIntegrationChangePasswordRequest request) {
            return base.Channel.NiraIntegrationChangePassword(request);
        }
        
        public string NiraIntegrationChangePassword(string NewPassword, string username, string password) {
            Maaif.WebReference.NiraIntegrationChangePasswordRequest inValue = new Maaif.WebReference.NiraIntegrationChangePasswordRequest();
            inValue.Body = new Maaif.WebReference.NiraIntegrationChangePasswordRequestBody();
            inValue.Body.NewPassword = NewPassword;
            inValue.Body.username = username;
            inValue.Body.password = password;
            Maaif.WebReference.NiraIntegrationChangePasswordResponse retVal = ((Maaif.WebReference.WebServiceSoap)(this)).NiraIntegrationChangePassword(inValue);
            return retVal.Body.NiraIntegrationChangePasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Maaif.WebReference.NiraIntegrationChangePasswordResponse> Maaif.WebReference.WebServiceSoap.NiraIntegrationChangePasswordAsync(Maaif.WebReference.NiraIntegrationChangePasswordRequest request) {
            return base.Channel.NiraIntegrationChangePasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<Maaif.WebReference.NiraIntegrationChangePasswordResponse> NiraIntegrationChangePasswordAsync(string NewPassword, string username, string password) {
            Maaif.WebReference.NiraIntegrationChangePasswordRequest inValue = new Maaif.WebReference.NiraIntegrationChangePasswordRequest();
            inValue.Body = new Maaif.WebReference.NiraIntegrationChangePasswordRequestBody();
            inValue.Body.NewPassword = NewPassword;
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((Maaif.WebReference.WebServiceSoap)(this)).NiraIntegrationChangePasswordAsync(inValue);
        }
    }
}
